### ISSUE TITLE
AnswerInlineQuery's List constructor parameter should be changed to support inheritance

### ISSUE THREAD

**Issue by bo0tzz** [jTelegram/jTelegramBotAPI#21]
Currently the AnswerInlineQuery constructor takes a `List<InlineResult>` as parameter ([AnswerInlineQuery#L21](https://github.com/jTelegram/jTelegramBotAPI/blob/master/jtelegrambotapi-core/src/main/java/com/jtelegram/api/requests/inline/AnswerInlineQuery.java#L21)).
This should be changed to a `List<? extends InlineResult>` to allow users to pass in, for example, a `List<InlineResultPhoto>`.

A similar issue may exist in other locations where a List is accepted as part of constructor parameters.

**Comment by mkotb** [comment]
Hi!

Sorry for the late response, it's been a busy week for me. I understand your point here, but my concern is that if I do change go through with those changes, it will lock in users into using only one type of InlineResult, while Telegram supports multiple different types being sent in the same response if I'm not mistaken. My inclination is to use generics here, but that could get messy as we instantiate the request using a builder. The other option is, for the sake of simplicity, keep it as is.

I'm interested to hear your thoughts between the options here.

Thanks!

**Comment by aaomidi** [comment]
So this is one of the edgiest cases in Java. I'll let Mazen explain but I'm kinda mindblown.
