### ISSUE TITLE
User class does not have a toString implementation

### ISSUE THREAD

**Issue by bo0tzz** [jTelegram/jTelegramBotAPI#24]
The com.jtelegram.api.user.User class does not have a toString implementation. This means that a line of code such as:
```java
LOGGER.debug("Received new inline query: {} from user {}.", query, inlineQueryEvent.getQuery().getFrom());
```
Results in a logging line such as:
`BootyTestingBot_1  | 87484984 [pool-1-thread-7] DEBUG com.bo0tzz.imagebot.handler.InlineQueryHandler  - Received new inline query: this is broken from user com.jtelegram.api.user.User@34d42ff.
`

**Comment by aaomidi** [comment]
This was fixed through https://github.com/jTelegram/jTelegramBotAPI/pull/26 and another commit that I'm too lazy to go search.
